//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_UAG_CFDI_CNFG_V
    {
        public string SETID { get; set; }
        public string BUSINESS_UNIT { get; set; }
        public string UAG_CFDI_RECEPTRFC { get; set; }
        public decimal OPEN_YEAR_FROM { get; set; }
        public decimal OPEN_PERIOD_FROM { get; set; }
        public Nullable<System.DateTime> OPEN_FROM_DATE { get; set; }
        public decimal OPEN_YEAR_TO { get; set; }
        public decimal OPEN_PERIOD_TO { get; set; }
        public Nullable<System.DateTime> OPEN_TO_DATE { get; set; }
        public string FO_USERID { get; set; }
        public string FO_PASSWORD { get; set; }
    }
}
