//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_UAG_REF_BNK_TBL
    {
        public string GUID { get; set; }
        public string SOURCE_REQ { get; set; }
        public decimal ID_SEQ_NUM { get; set; }
        public string UAG_BNK_ID_REF { get; set; }
        public string DOCUMENT_ID { get; set; }
        public decimal DAYS_DURATION { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
