//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_COMPAG_PYMNT
    {
        public string UAG_COMPAG_UUID { get; set; }
        public decimal UAG_COMPAG_LN { get; set; }
        public string UAG_COMPAG_CTABEN { get; set; }
        public string UAG_COMPAG_CTABENRFC { get; set; }
        public string UAG_COMPAG_CTAORD { get; set; }
        public string UAG_COMPAG_CTAORDRFC { get; set; }
        public string UAG_COMPAG_NUMOPR { get; set; }
        public decimal UAG_COMPAG_MONTO { get; set; }
        public string UAG_COMPAG_MONEDA { get; set; }
        public string UAG_COMPAG_FORMAPAG { get; set; }
        public System.DateTime UAG_COMPAG_FECHAPAG { get; set; }
    }
}
