//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_COMPAG_LN
    {
        public string UAG_COMPAG_UUID { get; set; }
        public decimal UAG_COMPAG_NUM_LINEA { get; set; }
        public decimal UAG_COMPAG_IMPORTE { get; set; }
        public decimal UAG_COMPAG_VALORUNIT { get; set; }
        public string UAG_COMPAG_DESCR { get; set; }
        public string UAG_COMPAG_CLVUNIDAD { get; set; }
        public string UAG_COMPAG_PRODSERV { get; set; }
        public Nullable<decimal> UAG_COMPAG_QTY { get; set; }
    }
}
