//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_CFDI_IM_LOC
    {
        public string UAG_CFDI_UUID { get; set; }
        public decimal UAG_CFDI_NUM_LINEA { get; set; }
        public string UAG_CFDI_TIPOIMP { get; set; }
        public string UAG_CFDI_IMP_LOC { get; set; }
        public decimal UAG_CFDI_TASACUOTA { get; set; }
        public decimal UAG_CFDI_IMPORTE { get; set; }
    }
}
