//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_CFDI_LN
    {
        public string UAG_CFDI_UUID { get; set; }
        public decimal UAG_CFDI_NUM_LINEA { get; set; }
        public string UAG_CFDI_PRODSERV { get; set; }
        public string UAG_CFDI_CLVUNIDAD { get; set; }
        public string UAG_CFDI_DESCR { get; set; }
        public decimal UAG_CFDI_VALORUNIT { get; set; }
        public decimal UAG_CFDI_IMPORTE { get; set; }
        public decimal UAG_CFDI_DESCUENTO { get; set; }
        public decimal UAG_CFDI_CANTIDAD { get; set; }
    }
}
