//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_COMPAG_HDR
    {
        public string SOURCE { get; set; }
        public string UAG_COMPAG_UUID { get; set; }
        public string UAG_COMPAG_FOLIO { get; set; }
        public Nullable<System.DateTime> UAG_COMPAG_FECHA { get; set; }
        public string UAG_COMPAG_MONEDA { get; set; }
        public string UAG_COMPAG_SERIE { get; set; }
        public decimal UAG_COMPAG_SUBTOTAL { get; set; }
        public string UAG_COMPAG_TIPOCOMPR { get; set; }
        public decimal UAG_COMPAG_TOTAL { get; set; }
        public string UAG_COMPAG_VERSION { get; set; }
        public string UAG_COMPAG_EMISOR { get; set; }
        public string UAG_COMPAG_EMISORRFC { get; set; }
        public string UAG_COMPAG_EMISORREG { get; set; }
        public string UAG_COMPAG_RECEPTOR { get; set; }
        public string UAG_COMPAG_RECEPTORRFC { get; set; }
        public string UAG_COMPAG_USO { get; set; }
        public byte[] UAG_COMPAG_DOC { get; set; }
        public string UAG_COMPAG_FOLIOPROV { get; set; }
    }
}
