//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_CFDI_HDR
    {
        public string SOURCE { get; set; }
        public string UAG_CFDI_UUID { get; set; }
        public string UAG_CFDI_FOLIO { get; set; }
        public Nullable<System.DateTime> UAG_CFDI_FECHA { get; set; }
        public string UAG_CFDI_FORMAPAGO { get; set; }
        public string UAG_CFDI_METODOPAG { get; set; }
        public string UAG_CFDI_MONEDA { get; set; }
        public string UAG_CFDI_SERIE { get; set; }
        public decimal UAG_CFDI_SUBTOTAL { get; set; }
        public string UAG_CFDI_TIPOCOMPR { get; set; }
        public decimal UAG_CFDI_TOTAL { get; set; }
        public string UAG_CFDI_VERSION { get; set; }
        public string UAG_CFDI_EMISOR { get; set; }
        public string UAG_CFDI_EMISORRFC { get; set; }
        public string UAG_CFDI_EMISORREG { get; set; }
        public string UAG_CFDI_RECEPTOR { get; set; }
        public string UAG_CFDI_RECEPTRFC { get; set; }
        public string UAG_CFDI_USO { get; set; }
        public decimal UAG_CFDI_TIPOCAMBIO { get; set; }
        public byte[] UAG_CFDI_DOC { get; set; }
        public Nullable<short> UAG_CFDI_TOTAL_LINEAS { get; set; }
        public Nullable<short> UAG_CFDI_LINEAS_REL { get; set; }
        public Nullable<decimal> UAG_CFDI_IVA { get; set; }
        public string UAG_CFDI_FOLIOPROV { get; set; }
    }
}
