//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_COMPAG_PYMNT_DOCREL
    {
        public string UAG_COMPAG_UUID { get; set; }
        public decimal UAG_COMPAG_LN { get; set; }
        public decimal UAG_COMPAG_DOC_LN { get; set; }
        public string UAG_COMPAG_FOLIO { get; set; }
        public string UAG_COMPAG_SERIE { get; set; }
        public decimal UAG_COMPAG_SALINSO { get; set; }
        public decimal UAG_COMPAG_IMPPAG { get; set; }
        public decimal UAG_COMPAG_SALANTE { get; set; }
        public decimal UAG_COMPAG_NUMPAR { get; set; }
        public string UAG_COMPAG_METPAG { get; set; }
        public string UAG_COMPAG_MONEDA { get; set; }
        public string UAG_COMPAG_DOCREL { get; set; }
    }
}
