//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_UUID_LOG
    {
        public string SOURCE { get; set; }
        public string UAG_CFDI_UUID { get; set; }
        public System.DateTime UAG_LOG_FEC { get; set; }
        public string UAG_LOG_ACCCION { get; set; }
        public string UAG_LOG_DESCR { get; set; }
        public string UAG_LOG_IP { get; set; }
    }
}
