//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAG_VENDOR
    {
        public string VNDR_RFC { get; set; }
        public string VNDR_LOCATION { get; set; }
        public string VNDR_TYPE { get; set; }
        public string VNDR_NAME { get; set; }
        public string VENDOR_ID { get; set; }
        public string VNDR_PASSWORD { get; set; }
        public System.DateTime VNDR_CREATED_DTTM { get; set; }
        public System.DateTime VNDR_LAST_MODIFIED_DATE { get; set; }
        public string VNDR_STATUS { get; set; }
    }
}
