//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAGUtileriasSAT.solucionfactible {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.recepcion.cfd.solucionfactible.com")]
    public partial class SFERPApplicationError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SFERPApplicationError1 sFERPApplicationError1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SFERPApplicationError", IsNullable=true, Order=0)]
        public SFERPApplicationError1 SFERPApplicationError1 {
            get {
                return this.sFERPApplicationError1Field;
            }
            set {
                this.sFERPApplicationError1Field = value;
                this.RaisePropertyChanged("SFERPApplicationError1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SFERPApplicationError", Namespace="http://faults.ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class SFERPApplicationError1 : Exception {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SFERPApplicationError1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class RepresentacionImpresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaRecepcionField;
        
        private bool fechaRecepcionFieldSpecified;
        
        private string folioField;
        
        private string nombreArchivoField;
        
        private byte[] pdfField;
        
        private string serieField;
        
        private string uuidField;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> fechaRecepcion {
            get {
                return this.fechaRecepcionField;
            }
            set {
                this.fechaRecepcionField = value;
                this.RaisePropertyChanged("fechaRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRecepcionSpecified {
            get {
                return this.fechaRecepcionFieldSpecified;
            }
            set {
                this.fechaRecepcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaRecepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string nombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
                this.RaisePropertyChanged("nombreArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=4)]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("pdf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
                this.RaisePropertyChanged("validSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class RespuestaPDF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensajeField;
        
        private RepresentacionImpresa[] resultadosField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true, Order=1)]
        public RepresentacionImpresa[] resultados {
            get {
                return this.resultadosField;
            }
            set {
                this.resultadosField = value;
                this.RaisePropertyChanged("resultados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class ResumenCFD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string buzonField;
        
        private System.Nullable<bool> canceladoField;
        
        private bool canceladoFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaRecepcionField;
        
        private bool fechaRecepcionFieldSpecified;
        
        private string folioField;
        
        private string monedaField;
        
        private System.Nullable<decimal> monedaTipoCambioField;
        
        private bool monedaTipoCambioFieldSpecified;
        
        private string nombreEmisorField;
        
        private System.Nullable<bool> rechazadoField;
        
        private bool rechazadoFieldSpecified;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string serieField;
        
        private System.Nullable<decimal> subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private System.Nullable<int> tipoComprobanteField;
        
        private bool tipoComprobanteFieldSpecified;
        
        private System.Nullable<decimal> totalField;
        
        private bool totalFieldSpecified;
        
        private string uuidField;
        
        private System.Nullable<bool> validoField;
        
        private bool validoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string buzon {
            get {
                return this.buzonField;
            }
            set {
                this.buzonField = value;
                this.RaisePropertyChanged("buzon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> cancelado {
            get {
                return this.canceladoField;
            }
            set {
                this.canceladoField = value;
                this.RaisePropertyChanged("cancelado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canceladoSpecified {
            get {
                return this.canceladoFieldSpecified;
            }
            set {
                this.canceladoFieldSpecified = value;
                this.RaisePropertyChanged("canceladoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaRecepcion {
            get {
                return this.fechaRecepcionField;
            }
            set {
                this.fechaRecepcionField = value;
                this.RaisePropertyChanged("fechaRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRecepcionSpecified {
            get {
                return this.fechaRecepcionFieldSpecified;
            }
            set {
                this.fechaRecepcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaRecepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> monedaTipoCambio {
            get {
                return this.monedaTipoCambioField;
            }
            set {
                this.monedaTipoCambioField = value;
                this.RaisePropertyChanged("monedaTipoCambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monedaTipoCambioSpecified {
            get {
                return this.monedaTipoCambioFieldSpecified;
            }
            set {
                this.monedaTipoCambioFieldSpecified = value;
                this.RaisePropertyChanged("monedaTipoCambioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string nombreEmisor {
            get {
                return this.nombreEmisorField;
            }
            set {
                this.nombreEmisorField = value;
                this.RaisePropertyChanged("nombreEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> rechazado {
            get {
                return this.rechazadoField;
            }
            set {
                this.rechazadoField = value;
                this.RaisePropertyChanged("rechazado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rechazadoSpecified {
            get {
                return this.rechazadoFieldSpecified;
            }
            set {
                this.rechazadoFieldSpecified = value;
                this.RaisePropertyChanged("rechazadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("rfcEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string rfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("rfcReceptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoComprobanteSpecified {
            get {
                return this.tipoComprobanteFieldSpecified;
            }
            set {
                this.tipoComprobanteFieldSpecified = value;
                this.RaisePropertyChanged("tipoComprobanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> valido {
            get {
                return this.validoField;
            }
            set {
                this.validoField = value;
                this.RaisePropertyChanged("valido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validoSpecified {
            get {
                return this.validoFieldSpecified;
            }
            set {
                this.validoFieldSpecified = value;
                this.RaisePropertyChanged("validoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class RespuestaConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResumenCFD[] comprobantesField;
        
        private int maxField;
        
        private bool maxFieldSpecified;
        
        private string mensajeField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comprobantes", IsNullable=true, Order=0)]
        public ResumenCFD[] comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                this.comprobantesField = value;
                this.RaisePropertyChanged("comprobantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("max");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpecified {
            get {
                return this.maxFieldSpecified;
            }
            set {
                this.maxFieldSpecified = value;
                this.RaisePropertyChanged("maxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class ParametrosConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string buzonField;
        
        private bool excluyeCanceladosField;
        
        private bool excluyeCanceladosFieldSpecified;
        
        private bool excluyeNoValidosField;
        
        private bool excluyeNoValidosFieldSpecified;
        
        private bool excluyeRechazadosField;
        
        private bool excluyeRechazadosFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaEmisionFinField;
        
        private bool fechaEmisionFinFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaEmisionInicioField;
        
        private bool fechaEmisionInicioFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaRecepcionFinField;
        
        private bool fechaRecepcionFinFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaRecepcionInicioField;
        
        private bool fechaRecepcionInicioFieldSpecified;
        
        private string folioField;
        
        private int limitField;
        
        private bool limitFieldSpecified;
        
        private int offsetField;
        
        private bool offsetFieldSpecified;
        
        private string orderByField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string serieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string buzon {
            get {
                return this.buzonField;
            }
            set {
                this.buzonField = value;
                this.RaisePropertyChanged("buzon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool excluyeCancelados {
            get {
                return this.excluyeCanceladosField;
            }
            set {
                this.excluyeCanceladosField = value;
                this.RaisePropertyChanged("excluyeCancelados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool excluyeCanceladosSpecified {
            get {
                return this.excluyeCanceladosFieldSpecified;
            }
            set {
                this.excluyeCanceladosFieldSpecified = value;
                this.RaisePropertyChanged("excluyeCanceladosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool excluyeNoValidos {
            get {
                return this.excluyeNoValidosField;
            }
            set {
                this.excluyeNoValidosField = value;
                this.RaisePropertyChanged("excluyeNoValidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool excluyeNoValidosSpecified {
            get {
                return this.excluyeNoValidosFieldSpecified;
            }
            set {
                this.excluyeNoValidosFieldSpecified = value;
                this.RaisePropertyChanged("excluyeNoValidosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool excluyeRechazados {
            get {
                return this.excluyeRechazadosField;
            }
            set {
                this.excluyeRechazadosField = value;
                this.RaisePropertyChanged("excluyeRechazados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool excluyeRechazadosSpecified {
            get {
                return this.excluyeRechazadosFieldSpecified;
            }
            set {
                this.excluyeRechazadosFieldSpecified = value;
                this.RaisePropertyChanged("excluyeRechazadosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> fechaEmisionFin {
            get {
                return this.fechaEmisionFinField;
            }
            set {
                this.fechaEmisionFinField = value;
                this.RaisePropertyChanged("fechaEmisionFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionFinSpecified {
            get {
                return this.fechaEmisionFinFieldSpecified;
            }
            set {
                this.fechaEmisionFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> fechaEmisionInicio {
            get {
                return this.fechaEmisionInicioField;
            }
            set {
                this.fechaEmisionInicioField = value;
                this.RaisePropertyChanged("fechaEmisionInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionInicioSpecified {
            get {
                return this.fechaEmisionInicioFieldSpecified;
            }
            set {
                this.fechaEmisionInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> fechaRecepcionFin {
            get {
                return this.fechaRecepcionFinField;
            }
            set {
                this.fechaRecepcionFinField = value;
                this.RaisePropertyChanged("fechaRecepcionFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRecepcionFinSpecified {
            get {
                return this.fechaRecepcionFinFieldSpecified;
            }
            set {
                this.fechaRecepcionFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaRecepcionFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> fechaRecepcionInicio {
            get {
                return this.fechaRecepcionInicioField;
            }
            set {
                this.fechaRecepcionInicioField = value;
                this.RaisePropertyChanged("fechaRecepcionInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRecepcionInicioSpecified {
            get {
                return this.fechaRecepcionInicioFieldSpecified;
            }
            set {
                this.fechaRecepcionInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaRecepcionInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitSpecified {
            get {
                return this.limitFieldSpecified;
            }
            set {
                this.limitFieldSpecified = value;
                this.RaisePropertyChanged("limitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
                this.RaisePropertyChanged("offsetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string orderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
                this.RaisePropertyChanged("orderBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("rfcEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string rfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("rfcReceptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntregaCustom))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class Entrega : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuseField;
        
        private string cfdiIdField;
        
        private string mensajeField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
                this.RaisePropertyChanged("acuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cfdiId {
            get {
                return this.cfdiIdField;
            }
            set {
                this.cfdiIdField = value;
                this.RaisePropertyChanged("cfdiId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class EntregaCustom : Entrega {
        
        private CampoPersonalizado[] customValuesReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customValuesReturn", IsNullable=true, Order=0)]
        public CampoPersonalizado[] customValuesReturn {
            get {
                return this.customValuesReturnField;
            }
            set {
                this.customValuesReturnField = value;
                this.RaisePropertyChanged("customValuesReturn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com/xsd")]
    public partial class CampoPersonalizado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", ConfigurationName="solucionfactible.RecibeCFDPortType")]
    public interface RecibeCFDPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:recibeCFDCustom", ReplyAction="urn:recibeCFDCustomResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:recibeCFDCustomSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.recibeCFDCustomResponse recibeCFDCustom(UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:recibeCFDCustom", ReplyAction="urn:recibeCFDCustomResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDCustomResponse> recibeCFDCustomAsync(UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:obtenerPDF", ReplyAction="urn:obtenerPDFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:obtenerPDFSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.obtenerPDFResponse obtenerPDF(UAGUtileriasSAT.solucionfactible.obtenerPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:obtenerPDF", ReplyAction="urn:obtenerPDFResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.obtenerPDFResponse> obtenerPDFAsync(UAGUtileriasSAT.solucionfactible.obtenerPDFRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:recibeCFDEnBuzon", ReplyAction="urn:recibeCFDEnBuzonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:recibeCFDEnBuzonSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonResponse recibeCFDEnBuzon(UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:recibeCFDEnBuzon", ReplyAction="urn:recibeCFDEnBuzonResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonResponse> recibeCFDEnBuzonAsync(UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultar", ReplyAction="urn:consultarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:consultarSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.consultarResponse consultar(UAGUtileriasSAT.solucionfactible.consultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultar", ReplyAction="urn:consultarResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.consultarResponse> consultarAsync(UAGUtileriasSAT.solucionfactible.consultarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:rechazarAddendaCFD", ReplyAction="urn:rechazarAddendaCFDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:rechazarAddendaCFDSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDResponse rechazarAddendaCFD(UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:rechazarAddendaCFD", ReplyAction="urn:rechazarAddendaCFDResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDResponse> rechazarAddendaCFDAsync(UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:rechazarCFD", ReplyAction="urn:rechazarCFDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:rechazarCFDSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.rechazarCFDResponse rechazarCFD(UAGUtileriasSAT.solucionfactible.rechazarCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:rechazarCFD", ReplyAction="urn:rechazarCFDResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.rechazarCFDResponse> rechazarCFDAsync(UAGUtileriasSAT.solucionfactible.rechazarCFDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:recibeCFD", ReplyAction="urn:recibeCFDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UAGUtileriasSAT.solucionfactible.SFERPApplicationError), Action="urn:recibeCFDSFERPApplicationError", Name="SFERPApplicationError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaPDF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParametrosConsulta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entrega))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UAGUtileriasSAT.solucionfactible.recibeCFDResponse recibeCFD(UAGUtileriasSAT.solucionfactible.recibeCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:recibeCFD", ReplyAction="urn:recibeCFDResponse")]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDResponse> recibeCFDAsync(UAGUtileriasSAT.solucionfactible.recibeCFDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recibeCFDCustom", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class recibeCFDCustomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cfd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreArchivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreBuzon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("camposPersonalizados", IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados;
        
        public recibeCFDCustomRequest() {
        }
        
        public recibeCFDCustomRequest(string usuario, string password, byte[] cfd, string nombreArchivo, string nombreBuzon, UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados) {
            this.usuario = usuario;
            this.password = password;
            this.cfd = cfd;
            this.nombreArchivo = nombreArchivo;
            this.nombreBuzon = nombreBuzon;
            this.camposPersonalizados = camposPersonalizados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recibeCFDCustomResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class recibeCFDCustomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.EntregaCustom @return;
        
        public recibeCFDCustomResponse() {
        }
        
        public recibeCFDCustomResponse(UAGUtileriasSAT.solucionfactible.EntregaCustom @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPDF", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class obtenerPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=6)]
        public long ridDiseno;
        
        public obtenerPDFRequest() {
        }
        
        public obtenerPDFRequest(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, long ridDiseno) {
            this.usuario = usuario;
            this.password = password;
            this.rfcEmisor = rfcEmisor;
            this.folio = folio;
            this.serie = serie;
            this.uuid = uuid;
            this.ridDiseno = ridDiseno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPDFResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class obtenerPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.RespuestaPDF @return;
        
        public obtenerPDFResponse() {
        }
        
        public obtenerPDFResponse(UAGUtileriasSAT.solucionfactible.RespuestaPDF @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recibeCFDEnBuzon", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class recibeCFDEnBuzonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cfd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreArchivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreBuzon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("camposPersonalizados", IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados;
        
        public recibeCFDEnBuzonRequest() {
        }
        
        public recibeCFDEnBuzonRequest(string usuario, string password, byte[] cfd, string nombreArchivo, string nombreBuzon, UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados) {
            this.usuario = usuario;
            this.password = password;
            this.cfd = cfd;
            this.nombreArchivo = nombreArchivo;
            this.nombreBuzon = nombreBuzon;
            this.camposPersonalizados = camposPersonalizados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recibeCFDEnBuzonResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class recibeCFDEnBuzonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.Entrega @return;
        
        public recibeCFDEnBuzonResponse() {
        }
        
        public recibeCFDEnBuzonResponse(UAGUtileriasSAT.solucionfactible.Entrega @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class consultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.ParametrosConsulta parametrosConsulta;
        
        public consultarRequest() {
        }
        
        public consultarRequest(string usuario, string password, UAGUtileriasSAT.solucionfactible.ParametrosConsulta parametrosConsulta) {
            this.usuario = usuario;
            this.password = password;
            this.parametrosConsulta = parametrosConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class consultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.RespuestaConsulta @return;
        
        public consultarResponse() {
        }
        
        public consultarResponse(UAGUtileriasSAT.solucionfactible.RespuestaConsulta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rechazarAddendaCFD", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class rechazarAddendaCFDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string correo;
        
        public rechazarAddendaCFDRequest() {
        }
        
        public rechazarAddendaCFDRequest(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, string mensaje, string correo) {
            this.usuario = usuario;
            this.password = password;
            this.rfcEmisor = rfcEmisor;
            this.folio = folio;
            this.serie = serie;
            this.uuid = uuid;
            this.mensaje = mensaje;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rechazarAddendaCFDResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class rechazarAddendaCFDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.Entrega @return;
        
        public rechazarAddendaCFDResponse() {
        }
        
        public rechazarAddendaCFDResponse(UAGUtileriasSAT.solucionfactible.Entrega @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rechazarCFD", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class rechazarCFDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string correo;
        
        public rechazarCFDRequest() {
        }
        
        public rechazarCFDRequest(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, string mensaje, string correo) {
            this.usuario = usuario;
            this.password = password;
            this.rfcEmisor = rfcEmisor;
            this.folio = folio;
            this.serie = serie;
            this.uuid = uuid;
            this.mensaje = mensaje;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rechazarCFDResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class rechazarCFDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.Entrega @return;
        
        public rechazarCFDResponse() {
        }
        
        public rechazarCFDResponse(UAGUtileriasSAT.solucionfactible.Entrega @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recibeCFD", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class recibeCFDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cfd;
        
        public recibeCFDRequest() {
        }
        
        public recibeCFDRequest(string usuario, string password, byte[] cfd) {
            this.usuario = usuario;
            this.password = password;
            this.cfd = cfd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recibeCFDResponse", WrapperNamespace="http://ws.recepcion.cfd.solucionfactible.com", IsWrapped=true)]
    public partial class recibeCFDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.recepcion.cfd.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UAGUtileriasSAT.solucionfactible.Entrega @return;
        
        public recibeCFDResponse() {
        }
        
        public recibeCFDResponse(UAGUtileriasSAT.solucionfactible.Entrega @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecibeCFDPortTypeChannel : UAGUtileriasSAT.solucionfactible.RecibeCFDPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecibeCFDPortTypeClient : System.ServiceModel.ClientBase<UAGUtileriasSAT.solucionfactible.RecibeCFDPortType>, UAGUtileriasSAT.solucionfactible.RecibeCFDPortType {
        
        public RecibeCFDPortTypeClient() {
        }
        
        public RecibeCFDPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecibeCFDPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecibeCFDPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecibeCFDPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.recibeCFDCustomResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.recibeCFDCustom(UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest request) {
            return base.Channel.recibeCFDCustom(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.EntregaCustom recibeCFDCustom(string usuario, string password, byte[] cfd, string nombreArchivo, string nombreBuzon, UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados) {
            UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest inValue = new UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfd = cfd;
            inValue.nombreArchivo = nombreArchivo;
            inValue.nombreBuzon = nombreBuzon;
            inValue.camposPersonalizados = camposPersonalizados;
            UAGUtileriasSAT.solucionfactible.recibeCFDCustomResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).recibeCFDCustom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDCustomResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.recibeCFDCustomAsync(UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest request) {
            return base.Channel.recibeCFDCustomAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDCustomResponse> recibeCFDCustomAsync(string usuario, string password, byte[] cfd, string nombreArchivo, string nombreBuzon, UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados) {
            UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest inValue = new UAGUtileriasSAT.solucionfactible.recibeCFDCustomRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfd = cfd;
            inValue.nombreArchivo = nombreArchivo;
            inValue.nombreBuzon = nombreBuzon;
            inValue.camposPersonalizados = camposPersonalizados;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).recibeCFDCustomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.obtenerPDFResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.obtenerPDF(UAGUtileriasSAT.solucionfactible.obtenerPDFRequest request) {
            return base.Channel.obtenerPDF(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.RespuestaPDF obtenerPDF(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, long ridDiseno) {
            UAGUtileriasSAT.solucionfactible.obtenerPDFRequest inValue = new UAGUtileriasSAT.solucionfactible.obtenerPDFRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.folio = folio;
            inValue.serie = serie;
            inValue.uuid = uuid;
            inValue.ridDiseno = ridDiseno;
            UAGUtileriasSAT.solucionfactible.obtenerPDFResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).obtenerPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.obtenerPDFResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.obtenerPDFAsync(UAGUtileriasSAT.solucionfactible.obtenerPDFRequest request) {
            return base.Channel.obtenerPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.obtenerPDFResponse> obtenerPDFAsync(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, long ridDiseno) {
            UAGUtileriasSAT.solucionfactible.obtenerPDFRequest inValue = new UAGUtileriasSAT.solucionfactible.obtenerPDFRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.folio = folio;
            inValue.serie = serie;
            inValue.uuid = uuid;
            inValue.ridDiseno = ridDiseno;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).obtenerPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.recibeCFDEnBuzon(UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest request) {
            return base.Channel.recibeCFDEnBuzon(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.Entrega recibeCFDEnBuzon(string usuario, string password, byte[] cfd, string nombreArchivo, string nombreBuzon, UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados) {
            UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest inValue = new UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfd = cfd;
            inValue.nombreArchivo = nombreArchivo;
            inValue.nombreBuzon = nombreBuzon;
            inValue.camposPersonalizados = camposPersonalizados;
            UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).recibeCFDEnBuzon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.recibeCFDEnBuzonAsync(UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest request) {
            return base.Channel.recibeCFDEnBuzonAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonResponse> recibeCFDEnBuzonAsync(string usuario, string password, byte[] cfd, string nombreArchivo, string nombreBuzon, UAGUtileriasSAT.solucionfactible.CampoPersonalizado[] camposPersonalizados) {
            UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest inValue = new UAGUtileriasSAT.solucionfactible.recibeCFDEnBuzonRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfd = cfd;
            inValue.nombreArchivo = nombreArchivo;
            inValue.nombreBuzon = nombreBuzon;
            inValue.camposPersonalizados = camposPersonalizados;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).recibeCFDEnBuzonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.consultarResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.consultar(UAGUtileriasSAT.solucionfactible.consultarRequest request) {
            return base.Channel.consultar(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.RespuestaConsulta consultar(string usuario, string password, UAGUtileriasSAT.solucionfactible.ParametrosConsulta parametrosConsulta) {
            UAGUtileriasSAT.solucionfactible.consultarRequest inValue = new UAGUtileriasSAT.solucionfactible.consultarRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.parametrosConsulta = parametrosConsulta;
            UAGUtileriasSAT.solucionfactible.consultarResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).consultar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.consultarResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.consultarAsync(UAGUtileriasSAT.solucionfactible.consultarRequest request) {
            return base.Channel.consultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.consultarResponse> consultarAsync(string usuario, string password, UAGUtileriasSAT.solucionfactible.ParametrosConsulta parametrosConsulta) {
            UAGUtileriasSAT.solucionfactible.consultarRequest inValue = new UAGUtileriasSAT.solucionfactible.consultarRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.parametrosConsulta = parametrosConsulta;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).consultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.rechazarAddendaCFD(UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest request) {
            return base.Channel.rechazarAddendaCFD(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.Entrega rechazarAddendaCFD(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, string mensaje, string correo) {
            UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest inValue = new UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.folio = folio;
            inValue.serie = serie;
            inValue.uuid = uuid;
            inValue.mensaje = mensaje;
            inValue.correo = correo;
            UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).rechazarAddendaCFD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.rechazarAddendaCFDAsync(UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest request) {
            return base.Channel.rechazarAddendaCFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDResponse> rechazarAddendaCFDAsync(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, string mensaje, string correo) {
            UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest inValue = new UAGUtileriasSAT.solucionfactible.rechazarAddendaCFDRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.folio = folio;
            inValue.serie = serie;
            inValue.uuid = uuid;
            inValue.mensaje = mensaje;
            inValue.correo = correo;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).rechazarAddendaCFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.rechazarCFDResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.rechazarCFD(UAGUtileriasSAT.solucionfactible.rechazarCFDRequest request) {
            return base.Channel.rechazarCFD(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.Entrega rechazarCFD(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, string mensaje, string correo) {
            UAGUtileriasSAT.solucionfactible.rechazarCFDRequest inValue = new UAGUtileriasSAT.solucionfactible.rechazarCFDRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.folio = folio;
            inValue.serie = serie;
            inValue.uuid = uuid;
            inValue.mensaje = mensaje;
            inValue.correo = correo;
            UAGUtileriasSAT.solucionfactible.rechazarCFDResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).rechazarCFD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.rechazarCFDResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.rechazarCFDAsync(UAGUtileriasSAT.solucionfactible.rechazarCFDRequest request) {
            return base.Channel.rechazarCFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.rechazarCFDResponse> rechazarCFDAsync(string usuario, string password, string rfcEmisor, string folio, string serie, string uuid, string mensaje, string correo) {
            UAGUtileriasSAT.solucionfactible.rechazarCFDRequest inValue = new UAGUtileriasSAT.solucionfactible.rechazarCFDRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.folio = folio;
            inValue.serie = serie;
            inValue.uuid = uuid;
            inValue.mensaje = mensaje;
            inValue.correo = correo;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).rechazarCFDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UAGUtileriasSAT.solucionfactible.recibeCFDResponse UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.recibeCFD(UAGUtileriasSAT.solucionfactible.recibeCFDRequest request) {
            return base.Channel.recibeCFD(request);
        }
        
        public UAGUtileriasSAT.solucionfactible.Entrega recibeCFD(string usuario, string password, byte[] cfd) {
            UAGUtileriasSAT.solucionfactible.recibeCFDRequest inValue = new UAGUtileriasSAT.solucionfactible.recibeCFDRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfd = cfd;
            UAGUtileriasSAT.solucionfactible.recibeCFDResponse retVal = ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).recibeCFD(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDResponse> UAGUtileriasSAT.solucionfactible.RecibeCFDPortType.recibeCFDAsync(UAGUtileriasSAT.solucionfactible.recibeCFDRequest request) {
            return base.Channel.recibeCFDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UAGUtileriasSAT.solucionfactible.recibeCFDResponse> recibeCFDAsync(string usuario, string password, byte[] cfd) {
            UAGUtileriasSAT.solucionfactible.recibeCFDRequest inValue = new UAGUtileriasSAT.solucionfactible.recibeCFDRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfd = cfd;
            return ((UAGUtileriasSAT.solucionfactible.RecibeCFDPortType)(this)).recibeCFDAsync(inValue);
        }
    }
}
